[tool.poetry]
name = "sklearn-nature-inspired-algorithms-timzatko"
version = "0.1.0"
description = "Search using nature inspired algorithms over specified parameter values for an sklearn estimator."

license = "MIT"

authors = [
    "Timotej Zatko <timi.zatko@gmail.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms"
homepage = "https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms"

keywords = ['sklearn', 'nature', 'inspired', 'algorithms']

[tool.poetry.dependencies]
python = "^3.5"  # Compatible python versions must be declared here
toml = "^0.9"

NiaPy = { version = "2.0.0rc10" }
scikit-learn = "^0.22.2"
numpy = "^1.18.4"

[tool.poetry.dev-dependencies]
