[tool.poetry]
name = "sklearn-nature-inspired-search-timzatko"
version = "0.1.0"
description = "The description of the package"

license = "MIT"

authors = [
    "Timotej Zatko <timi.zatko@gmail.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/timzatko/Sklearn-Nature-Inspired-Search"
homepage = "https://github.com/timzatko/Sklearn-Nature-Inspired-Search"

keywords = ['sklearn', 'nature', 'inspired', 'genetic', 'algorithms']

[tool.poetry.dependencies]
python = "^3.5"  # Compatible python versions must be declared here
toml = "^0.9"

NiaPy = { version = "2.0.0rc10" }
scikit-learn = "^0.22.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
